### ISSUE TITLE
Moving to Quarkus 3?

### ISSUE THREAD

**Issue by gsmet** [quarkiverse/quarkus-reactive-mysql-pool-client#9]
Hi,

I was wondering if this extension was still needed now that Quarkus 3 supports the ability to define several connection URLs and handle a pool of connections?

If it's still necessary, I can provide a PR to upgrade it to Quarkus 3. But if not, let's retire it.

Thanks.

**Comment by benstonezhang** [comment]
This extension is not need for Quarkus 3. But please let it keep for some days in case I may have some bug fix on it.
Thx.

**Comment by gsmet** [comment]
@benstonezhang yes, I think we can keep it for a while as Quarkus 2.x will live for some time. I just wanted to know if I needed to upgrade it.

Thanks!
